---
- name: Update Cisco 9K switch RADIUS configuration 
  hosts:
    - all
  connection: local
  gather_facts: no

  - tasks:
    - name: run show version on remote devices
      cisco.ios.ios_command:
        commands: show version 

      register: print_output

    - debug: var=print_output

