---
## Configure Cisco CAT9K switches to receive SCP transfers initiated by a
# server.  Global configuration command "ip scp server enable" must be 
# added to the config.

- name: Add SCP server enable command to Cisco CAT9K switches
  hosts: cisco_cat9k 
  gather_facts: False
  connection: network_cli

  tasks:
    - name: Add SCP command and save running-config to startup-config
      ios_config:
        lines:
        - ip scp server enable 

    - name: Save running-config to startup-config when config is modified
      ios_config:
        save_when: modified
