---
- name: Generate and Install ISP Interface Descriptors
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "emea-tmp"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf"

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no

    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - name: Confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory
      run_once: yes

    - name: Save device information using template
      template:
        src: ~/git_wework/net-scripts/Ansible/juniper/templates/reth1-description.j2
        dest: "{{ conf_file }}"

    - name: Install generated configuration file onto device
      juniper_junos_config:
        provider:
          host: "{{ ansible_host }}"
          user: "{{ username }}"
          passwd: "{{ password }}"
          port: 22
          timeout: 120
        src: "{{ conf_file }}"
        load: set 
        comment: "[Add ISP description][reth1.0 interface only]"

